# Generated by Django 4.2.7 on 2023-12-05 01:04

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_quote', models.CharField(default='Make it work, make it right, make it fast', max_length=255)),
                ('bio', models.TextField()),
                ('short_bio', models.TextField(blank=True, null=True)),
                ('is_favorite', models.BooleanField(default=False)),
                ('pic', django_resized.forms.ResizedImageField(crop=None, default='user_pic/default.png', force_format=None, keep_meta=True, quality=-1, scale=None, size=[1920, 1080], upload_to='user_pic')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('percentage', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('icon', models.CharField(max_length=255)),
                ('profile_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='userprofile.profileitem')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('study', models.CharField(max_length=255)),
                ('institution_name', models.CharField(max_length=255)),
                ('profile_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='userprofile.profileitem')),
            ],
        ),
    ]
