# Generated by Django 4.2.7 on 2023-11-25 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileitem',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
