# Generated by Django 4.2.7 on 2023-12-20 05:34

from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_project_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('short_desc', models.TextField()),
                ('desc', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(max_length=200)),
                ('pic', django_resized.forms.ResizedImageField(crop=None, default='service_default.png', force_format=None, keep_meta=True, quality=-1, scale=None, size=[1920, 1080], upload_to='service')),
                ('completed_projects', models.PositiveIntegerField()),
                ('profile_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='userprofile.profileitem')),
            ],
        ),
    ]
