# Generated by Django 4.2.7 on 2023-11-28 00:26

from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_profileitem_is_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileitem',
            name='contact_info',
        ),
        migrations.RemoveField(
            model_name='profileitem',
            name='education',
        ),
        migrations.RemoveField(
            model_name='profileitem',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='profileitem',
            name='name',
        ),
        migrations.RemoveField(
            model_name='profileitem',
            name='skills',
        ),
        migrations.AddField(
            model_name='profileitem',
            name='main_quote',
            field=models.CharField(default='Make it work, make it right, make it fast', max_length=255),
        ),
        migrations.AddField(
            model_name='profileitem',
            name='pic',
            field=django_resized.forms.ResizedImageField(crop=None, default='user_pic/default.png', force_format=None, keep_meta=True, quality=-1, scale=None, size=[1920, 1080], upload_to='user_pic'),
        ),
        migrations.AddField(
            model_name='profileitem',
            name='short_bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('study', models.CharField(max_length=255)),
                ('institution_name', models.CharField(max_length=255)),
                ('profile_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='userprofile.profileitem')),
            ],
        ),
    ]
