# Generated by Django 4.2.7 on 2023-11-29 01:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_remove_profileitem_contact_info_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('percentage', models.PositiveIntegerField(verbose_name=django.core.validators.MaxValueValidator(100))),
                ('icon', models.CharField(max_length=255)),
                ('profile_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='userprofile.profileitem')),
            ],
        ),
    ]
