# Generated by Django 4.2.7 on 2023-12-20 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_alter_service_pic_alter_testimonial_client_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('budget', models.PositiveIntegerField(blank=True, null=True)),
                ('text', models.TextField()),
            ],
        ),
    ]
