# Generated by Django 4.2.7 on 2023-12-21 05:14

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0006_profileitem_completed_projects_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileitem',
            name='logo',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[1920, 1080], upload_to='logos'),
        ),
    ]
